//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Splat")]
[assembly: AssemblyVersion("2.1.0")]
[assembly: AssemblyFileVersion("2.1.0")]
[assembly: AssemblyInformationalVersion("2.1.0-alpha.1+Branch.develop.Sha.7dbf1d5e3745590ce4896e1a1d0ea3ada1be17eb")]
[assembly: AssemblyCopyright("Copyright (c) Paul Betts")]

