//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Splat")]
[assembly: AssemblyVersion("1.7.0")]
[assembly: AssemblyFileVersion("1.7.0")]
[assembly: AssemblyInformationalVersion("1.7.0-alpha.89+Branch.develop.Sha.c1e6e78afeb6de65d597afa5907e9e266fb9ce7e")]
[assembly: AssemblyCopyright("Copyright (c) Paul Betts")]

