// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Diagnostics.CodeAnalysis;
using System.Linq.Expressions;

using DryIoc;

namespace Splat.DryIoc;

/// <summary>
/// Provides an implementation of the IDependencyResolver interface using a DryIoc container for dependency resolution
/// and registration.
/// https://bitbucket.org/dadhi/dryioc/wiki/Home.
/// </summary>
/// <remarks>This resolver enables integration with DryIoc for managing service lifetimes and contracts. If no
/// container is supplied, the resolver creates and manages its own internal container instance. Thread safety and
/// disposal of the underlying container are managed by this class.</remarks>
/// <param name="container">The DryIoc container to use for service resolution and registration. If null, a new container instance is created.</param>
[SuppressMessage(
    "StyleSharp",
    "SST2307:A generic method's type parameter appears in no parameter, so no caller can infer it",
    Justification = "The generic parameter is the caller-supplied service type for resolution/registration; it cannot appear in the parameter list without changing the public interface contract.")]
public class DryIocDependencyResolver(IContainer? container = null) : IDependencyResolver
{
    /// <summary>Prefix used to synthesize service keys for registrations made without an explicit contract.</summary>
    private const string DefaultKeyPrefix = "DefaultKey";

    /// <summary>The underlying DryIoc container used for registration and resolution.</summary>
    private readonly IContainer _container = container ?? new Container();

    /// <inheritdoc />
    public virtual object? GetService(Type? serviceType, string? contract) =>
        GetServices(serviceType, contract).LastOrDefault();

    /// <inheritdoc/>
    public object? GetService(Type? serviceType) =>
        GetService(serviceType, null);

    /// <inheritdoc/>
    public T? GetService<T>() =>
        (T?)GetService(typeof(T), null);

    /// <inheritdoc/>
    public T? GetService<T>(string? contract) =>
        (T?)GetService(typeof(T), contract);

    /// <inheritdoc />
    public virtual IEnumerable<object> GetServices(Type? serviceType, string? contract)
    {
        // When contract is null/empty, get bindings with DefaultKey (auto-generated by AppendNewImplementation)
        if (string.IsNullOrEmpty(contract))
        {
            // Get all bindings that aren't tuple keys (which means they're either DefaultKey or null)
            var bindingsWithDefaultKey = _container.GetServiceRegistrations()
                .Where(x => x.ServiceType == serviceType && IsDefaultKey(x.OptionalServiceKey))
                .ToList();

            if (bindingsWithDefaultKey.Count == 0)
            {
                return [];
            }

            // Resolve each binding individually
            var results = new List<object>();
            foreach (var binding in bindingsWithDefaultKey)
            {
                var instance = _container.Resolve(serviceType, serviceKey: binding.OptionalServiceKey);
                if (instance is not null)
                {
                    results.Add(instance);
                }
            }

            return results;
        }

        // When contract is provided, resolve with the contract as the service key
        return _container.ResolveMany(serviceType, behavior: ResolveManyBehavior.AsFixedArray, serviceKey: contract);
    }

    /// <inheritdoc/>
    public IEnumerable<object> GetServices(Type? serviceType) =>
        GetServices(serviceType, null);

    /// <inheritdoc/>
    public IEnumerable<T> GetServices<T>() =>
        GetServices(typeof(T), null).Cast<T>();

    /// <inheritdoc/>
    public IEnumerable<T> GetServices<T>(string? contract) =>
        GetServices(typeof(T), contract).Cast<T>();

    /// <inheritdoc />
    public bool HasRegistration(Type? serviceType, string? contract)
    {
        ArgumentExceptionHelper.ThrowIfNull(serviceType);

        return _container.GetServiceRegistrations().Any(x =>
        {
            if (x.ServiceType != serviceType)
            {
                return false;
            }

            return contract is null ? IsDefaultKey(x.OptionalServiceKey) : x.OptionalServiceKey is string serviceKeyAsString &&
                   contract.Equals(serviceKeyAsString, StringComparison.Ordinal);
        });
    }

    /// <inheritdoc/>
    public bool HasRegistration(Type? serviceType) =>
        HasRegistration(serviceType, null);

    /// <inheritdoc/>
    public bool HasRegistration<T>() =>
        HasRegistration(typeof(T), null);

    /// <inheritdoc/>
    public bool HasRegistration<T>(string? contract) =>
        HasRegistration(typeof(T), contract);

    /// <inheritdoc />
    public virtual void Register(Func<object?> factory, Type? serviceType, string? contract)
    {
        ArgumentExceptionHelper.ThrowIfNull(factory);
        ArgumentExceptionHelper.ThrowIfNull(serviceType);

        if (string.IsNullOrEmpty(contract))
        {
            _container.RegisterDelegate(
                serviceType,
                _ => CreateThenConvert(serviceType, factory),
                ifAlreadyRegistered: IfAlreadyRegistered.AppendNewImplementation);

            return;
        }

        _container.RegisterDelegate(
            serviceType,
            _ => CreateThenConvert(serviceType, factory),
            ifAlreadyRegistered: IfAlreadyRegistered.Replace,
            serviceKey: contract);
    }

    /// <inheritdoc/>
    public void Register(Func<object?> factory, Type? serviceType) =>
        Register(factory, serviceType, null);

    /// <inheritdoc/>
    public void Register<T>(Func<T?> factory) =>
        Register(() => factory(), typeof(T), null);

    /// <inheritdoc/>
    public void Register<T>(Func<T?> factory, string? contract) =>
        Register(() => factory(), typeof(T), contract);

    /// <inheritdoc/>
    void IMutableDependencyResolver.Register<TService, TImplementation>() =>
        _container.RegisterDelegate<TService>(
            static _ => new TImplementation(),
            ifAlreadyRegistered: IfAlreadyRegistered.AppendNewImplementation);

    /// <inheritdoc/>
    void IMutableDependencyResolver.Register<TService, TImplementation>(string? contract)
    {
        if (string.IsNullOrEmpty(contract))
        {
            _container.RegisterDelegate<TService>(
                static _ => new TImplementation(),
                ifAlreadyRegistered: IfAlreadyRegistered.AppendNewImplementation);
            return;
        }

        _container.RegisterDelegate<TService>(
            static _ => new TImplementation(),
            ifAlreadyRegistered: IfAlreadyRegistered.Replace,
            serviceKey: contract);
    }

    /// <inheritdoc/>
    public void RegisterConstant<T>(T? value)
        where T : class
    {
        ArgumentExceptionHelper.ThrowIfNull(value);

        _container.RegisterInstance(
            value,
            ifAlreadyRegistered: IfAlreadyRegistered.AppendNewImplementation);
    }

    /// <inheritdoc/>
    public void RegisterConstant<T>(T? value, string? contract)
        where T : class
    {
        ArgumentExceptionHelper.ThrowIfNull(value);

        if (string.IsNullOrEmpty(contract))
        {
            _container.RegisterInstance(
                value,
                ifAlreadyRegistered: IfAlreadyRegistered.AppendNewImplementation);
            return;
        }

        _container.RegisterInstance(
            value,
            ifAlreadyRegistered: IfAlreadyRegistered.Replace,
            serviceKey: contract);
    }

    /// <inheritdoc/>
    public void RegisterLazySingleton<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] T>(Func<T?> valueFactory)
        where T : class
    {
        ArgumentExceptionHelper.ThrowIfNull(valueFactory);

        _container.RegisterDelegate(
            _ => valueFactory()!,
            Reuse.Singleton,
            ifAlreadyRegistered: IfAlreadyRegistered.AppendNewImplementation);
    }

    /// <inheritdoc/>
    public void RegisterLazySingleton<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] T>(Func<T?> valueFactory, string? contract)
        where T : class
    {
        ArgumentExceptionHelper.ThrowIfNull(valueFactory);

        if (string.IsNullOrEmpty(contract))
        {
            _container.RegisterDelegate(
                _ => valueFactory()!,
                Reuse.Singleton,
                ifAlreadyRegistered: IfAlreadyRegistered.AppendNewImplementation);
            return;
        }

        _container.RegisterDelegate(
            _ => valueFactory()!,
            Reuse.Singleton,
            ifAlreadyRegistered: IfAlreadyRegistered.Replace,
            serviceKey: contract);
    }

    /// <inheritdoc />
    public virtual void UnregisterCurrent(Type? serviceType, string? contract)
    {
        // Find the LAST matching binding (not the first)
        var matchingBinding = _container.GetServiceRegistrations()
            .LastOrDefault(x =>
            {
                if (x.ServiceType != serviceType)
                {
                    return false;
                }

                return contract is null ? IsDefaultKey(x.OptionalServiceKey) : x.OptionalServiceKey is string serviceKeyAsString &&
                       contract.Equals(serviceKeyAsString, StringComparison.Ordinal);
            });

        if (matchingBinding.Equals(default(ServiceRegistrationInfo)))
        {
            return;
        }

        // Unregister using the specific binding's key
        if (matchingBinding.OptionalServiceKey is not null)
        {
            _container.Unregister(serviceType, matchingBinding.OptionalServiceKey);
        }
        else
        {
            _container.Unregister(serviceType);
        }
    }

    /// <inheritdoc/>
    public void UnregisterCurrent(Type? serviceType) =>
        UnregisterCurrent(serviceType, null);

    /// <inheritdoc/>
    public void UnregisterCurrent<T>() =>
        UnregisterCurrent(typeof(T), null);

    /// <inheritdoc/>
    public void UnregisterCurrent<T>(string? contract) =>
        UnregisterCurrent(typeof(T), contract);

    /// <inheritdoc />
    public virtual void UnregisterAll(Type? serviceType, string? contract)
    {
        // Collect all registrations to unregister first to avoid modifying collection during iteration
        var registrationsToUnregister = _container.GetServiceRegistrations()
            .Where(x =>
            {
                if (x.ServiceType != serviceType)
                {
                    return false;
                }

                return contract is null ? IsDefaultKey(x.OptionalServiceKey) : x.OptionalServiceKey is string serviceKeyAsString &&
                       contract.Equals(serviceKeyAsString, StringComparison.Ordinal);
            })
            .ToList();

        // Unregister each collected registration
        foreach (var registration in registrationsToUnregister)
        {
            _container.Unregister(serviceType, registration.OptionalServiceKey);
        }
    }

    /// <inheritdoc/>
    public void UnregisterAll(Type? serviceType) =>
        UnregisterAll(serviceType, null);

    /// <inheritdoc/>
    public void UnregisterAll<T>() =>
        UnregisterAll(typeof(T), null);

    /// <inheritdoc/>
    public void UnregisterAll<T>(string? contract) =>
        UnregisterAll(typeof(T), contract);

    /// <inheritdoc />
    public virtual IDisposable ServiceRegistrationCallback(Type serviceType, string? contract, Action<IDisposable> callback)
        => throw new NotSupportedException("ServiceRegistrationCallback is not supported by the DryIocDependencyResolver.");

    /// <inheritdoc/>
    public IDisposable ServiceRegistrationCallback(Type serviceType, Action<IDisposable> callback) =>
        ServiceRegistrationCallback(serviceType, null, callback);

    /// <inheritdoc/>
    public IDisposable ServiceRegistrationCallback<T>(Action<IDisposable> callback) =>
        ServiceRegistrationCallback(typeof(T), null, callback);

    /// <inheritdoc/>
    public IDisposable ServiceRegistrationCallback<T>(string? contract, Action<IDisposable> callback) =>
        ServiceRegistrationCallback(typeof(T), contract, callback);

    /// <inheritdoc />
    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    /// <summary>Disposes of the instance.</summary>
    /// <param name="disposing">Whether or not the instance is disposing.</param>
    protected virtual void Dispose(bool disposing)
    {
        if (!disposing)
        {
            return;
        }

        try
        {
            DisposeContainer(_container);
        }
        catch (Exception ex)
        {
            // Suppress exceptions from service disposal
            System.Diagnostics.Debug.WriteLine(ex);
        }
    }

    /// <summary>Disposes the supplied container.</summary>
    /// <remarks>The null-conditional is a defensive guard: the container field is always assigned a non-null value at construction, so the null branch cannot be reached.</remarks>
    /// <param name="container">The container to dispose.</param>
    [ExcludeFromCodeCoverage]
    private static void DisposeContainer(IContainer? container) => container?.Dispose();

    /// <summary>Determines whether the supplied service key represents a contract-less (default) registration.</summary>
    /// <remarks>
    /// A registration made without an explicit contract has either a <see langword="null"/> service key (a single
    /// default registration) or a DryIoc auto-generated <c>DefaultKey</c> (when multiple default implementations are
    /// appended). Both cases must be treated as default registrations when resolving or unregistering without a contract.
    /// </remarks>
    /// <param name="serviceKey">The optional service key of a registration.</param>
    /// <returns><see langword="true"/> if the key is <see langword="null"/> or a DryIoc <c>DefaultKey</c>; otherwise <see langword="false"/>.</returns>
    private static bool IsDefaultKey(object? serviceKey) =>
        serviceKey is null || StartsWithDefaultKeyPrefix(serviceKey);

    /// <summary>Determines whether a non-null service key's string form is a DryIoc auto-generated default key.</summary>
    /// <remarks>
    /// The null-conditional on the rendered key is a defensive guard: DryIoc default keys and string contracts
    /// never render as <see langword="null"/>, so the null branch cannot be reached.
    /// </remarks>
    /// <param name="serviceKey">The non-null service key of a registration.</param>
    /// <returns><see langword="true"/> if the key's string form starts with the default-key prefix; otherwise <see langword="false"/>.</returns>
    [ExcludeFromCodeCoverage]
    private static bool StartsWithDefaultKeyPrefix(object serviceKey) =>
        serviceKey.ToString()?.StartsWith(DefaultKeyPrefix, StringComparison.Ordinal) == true;

    /// <summary>Invokes the factory and converts the produced instance to the requested service type.</summary>
    /// <param name="serviceType">The service type the instance should be converted to.</param>
    /// <param name="factory">The factory that creates the instance.</param>
    /// <returns>The created instance converted to <paramref name="serviceType"/>, or <see langword="null"/> if the factory returned <see langword="null"/>.</returns>
    private static object? CreateThenConvert(Type serviceType, Func<object?> factory)
    {
        // we need to cast because we pass an object back and dryioc wants it explicitly cast.
        // alternative (happy to be proven wrong) is to break the interface and add a Register<T>(...) method?
        var instance = factory();

        return instance is not null ? Cast(serviceType, instance) : null;
    }

    /// <summary>Casts the supplied data to the specified type using a compiled expression.</summary>
    /// <param name="type">The target type to cast the data to.</param>
    /// <param name="data">The data instance to cast.</param>
    /// <returns>The data cast to <paramref name="type"/>.</returns>
    private static object? Cast(Type type, object data)
    {
        // based upon https://stackoverflow.com/a/27584212
        var dataParam = Expression.Parameter(typeof(object), nameof(data));
        var body = Expression.Block(Expression.Convert(Expression.Convert(dataParam, data.GetType()), type));

        var run = Expression.Lambda(body, dataParam).Compile();
        return run.DynamicInvoke(data);
    }
}
