name: Common .NET setup and build workflow

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string

      productNamespacePrefix:
        required: true
        type: string

      useVisualStudioPreview:
        required: true
        type: boolean

      useMauiCheckDotNetTool:
        required: true
        type: boolean

      runTests:
        required: true
        type: boolean

      # nugetMode
      # 0: off
      # 1: pack and upload (CI build)
      # 2: sign and publish (Release action)
      nugetMode:
        required: true
        type: number

jobs:
  build:
    runs-on: windows-2022
    outputs:
      nbgv: ${{ steps.nbgv.outputs.SemVer2 }}
    steps:
    - name: Update Visual Studio preview
      if: inputs.useVisualStudioPreview == true
      shell: bash
      run: |
        dotnet tool update -g dotnet-vs
        vs update preview
        vs modify preview +mobile +desktop +uwp +web
        echo "##vso[task.prependpath]$(vs where preview --prop=InstallationPath)\MSBuild\Current\Bin"

    - name: Install Windows SDK 10.0.16299
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://go.microsoft.com/fwlink/p/?linkid=864422 -OutFile winsdk.exe
        $startInfo = New-Object System.Diagnostics.ProcessStartInfo
        $startInfo.FileName = "winsdk.exe"
        $startInfo.Arguments = "/norestart /quiet"
        $process = New-Object System.Diagnostics.Process
        $process.StartInfo = $startInfo
        $process.Start()
        $process.WaitForExit()

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 3.1.x

    - name: Install .NET 5
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 5.0.x

    - name: Install .NET 6
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Install DotNet workloads
      shell: bash
      run: |
        dotnet workload install android
        dotnet workload install ios
        dotnet workload install tvos
        dotnet workload install macos
        dotnet workload install maui

    - name: Run Maui Installation Check
      if: inputs.useMauiCheckDotNetTool == true
      shell: bash
      run: |
        dotnet tool install -g Redth.Net.Maui.Check
        maui-check --non-interactive --fix

    - name: Add MSBuild to PATH
      uses: glennawatson/setup-msbuild@v1.0.3
      with:
        prerelease: true

    - name: NBGV
      id: nbgv
      uses: dotnet/nbgv@master
      with:
        setAllVars: true

    - name: NuGet Restore
      run: dotnet restore
      working-directory: src

    - name: Build
      run: msbuild /t:build,pack /nowarn:MSB4011 /maxcpucount /p:NoPackageAnalysis=true /verbosity:minimal /p:Configuration=${{ inputs.configuration }}
      working-directory: src

    - name: Run Unit Tests and Generate Coverage
      if: inputs.runTests == true
      uses: glennawatson/coverlet-msbuild@v1
      with:
        project-files: '**/*Tests*.csproj'
        no-build: true
        exclude-filter: '[${{inputs.productNamespacePrefix}}.*.Tests.*]*,[${{inputs.productNamespacePrefix}}.Tests]*,[${{inputs.productNamespacePrefix}}.TestRunner.*]*'
        include-filter: '[${{inputs.productNamespacePrefix}}*]*'
        output-format: cobertura
        output: '../../artifacts/'
        configuration: ${{ inputs.configuration }}

    - name: Upload Code Coverage
      if: inputs.runTests == true
      shell: bash
      run: |
        echo $PWD
        bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy -t ${{ env.CODECOV_TOKEN }} -s '$PWD/artifacts' -f '*.xml'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Create NuGet Artifacts
      if: inputs.nugetMode == 1
      uses: actions/upload-artifact@master
      with:
        name: nuget
        path: '**/*.nupkg'
        
    - name: Save SignClient Configuration
      run: 'echo "$SIGN_CLIENT_CONFIG" > SignPackages.json'
      shell: bash
      env:
        SIGN_CLIENT_CONFIG: ${{secrets.SIGN_CLIENT_CONFIG}}

    - name: Sign NuGet Packages
      if: inputs.nugetMode == 2
      uses: glennawatson/signclient@v1
      with:
        input-files: '**/*.nupkg'
        sign-client-secret: ${{ secrets.SIGN_CLIENT_SECRET }}
        sign-client-user: ${{ secrets.SIGN_CLIENT_USER_ID }}
        project-name: reactiveui
        description: reactiveui
        config-file: SignPackages.json

    - name: Changelog
      if: inputs.nugetMode == 2
      uses: glennawatson/ChangeLog@v1
      id: changelog

    - name: Create Release
      if: inputs.nugetMode == 2
      uses: actions/create-release@v1.1.4
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: ${{ steps.nbgv.outputs.SemVer2 }}
          release_name: ${{ steps.nbgv.outputs.SemVer2 }}
          body: |
            ${{ steps.changelog.outputs.commitLog }}

    - name: NuGet Push
      if: inputs.nugetMode == 2
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
        SOURCE_URL: https://api.nuget.org/v3/index.json
      run: |
        dotnet nuget push -s ${{ env.SOURCE_URL }} -k ${{ env.NUGET_AUTH_TOKEN }} **/*.nupkg
